### ISSUE TITLE
Cannot read property 'is' of null

### ISSUE THREAD

**Issue by msokalski** [lapwinglabs/x-ray#113]
<pre>
d:\TVXAPI\node_modules\x-ray\lib\resolve.js:92
  if ($.is && $.is(selector)) return $;
       ^

TypeError: Cannot read property 'is' of null
    at select (d:\TVXAPI\node_modules\x-ray\lib\resolve.js:92:8)
    at find (d:\TVXAPI\node_modules\x-ray\lib\resolve.js:76:23)
    at resolve (d:\TVXAPI\node_modules\x-ray\lib\resolve.js:36:15)
    at node (d:\TVXAPI\node_modules\x-ray\index.js:90:19)
    at Request._callback (d:\TVXAPI\providers\bbc\main.js:420:7)
    at Request.self.callback (d:\TVXAPI\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (d:\TVXAPI\node_modules\request\request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
</pre>

**Comment by Kikobeats** [comment]
Please, open again the issue following the new issue template.

Thanks!

**Comment by markgibaud** [comment]
I get this error loads and have no idea where to start, was there any guidance?

Or should I open a new issue?
