### ISSUE TITLE
Uncaught ECONNRESET exception

### ISSUE THREAD

**Issue by paulshapiro** [lapwinglabs/x-ray#171]
### Subject of the issue

I found that the following apparently uncaught exception occurred and crashed our Node process instead of being caught by x-ray and forwarded as an err:

    events.js:154
          throw er; // Unhandled 'error' event
          ^
    
    Error: read ECONNRESET
        at exports._errnoException (util.js:890:11)
        at TCP.onread (net.js:552:26)

### Your environment

node v5.9.1
npm v3.7.3

### Steps to reproduce

Scrape from a source which resets the connection remotely.

### Expected behaviour

Expected exception to be caught by x-ray and passed to callback as err.

### Actual behaviour

Uncaught exception crashes process.

(PS many thanks for a great lib)

**Comment by paulshapiro** [comment]
Hm, I may be mistaken about x-ray being the source of this uncaught exception.
