### ISSUE TITLE
can't run tests on the current master branch

### ISSUE THREAD

**Issue by cosminonea** [lapwinglabs/x-ray#46]
I am trying to run the tests on the master branch and I get the following.

```
x-ray git:(master) ✗ make test
./x-ray/test/x-ray.js:103
  it('should be yieldable', function *() {
                                     ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at ./x-ray/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (./x-ray/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (./x-ray/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (./x-ray/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
make: *** [test] Error 1

```

**Comment by matthewmueller** [comment]
The tests require you to be running `node >= 0.11.0`. I'll add it to the Readme.

**Comment by cosminonea** [comment]
I am running 12.3

```
x-ray git:(master) ✗ which node
~/.nvm/versions/node/v0.12.3/bin/node
```

**Comment by matthewmueller** [comment]
ah my bad, updated `make test`, it should be fixed in master. thanks for the heads up!
