### ISSUE TITLE
 x(...).delay is not a function

### ISSUE THREAD

**Issue by ksidpen** [lapwinglabs/x-ray#96]
seems like the crawler delegate can't be reached? Or maybe I am just silly

<pre><code> 
Xray = require('x-ray');
var x = Xray()

x('https://dribbble.com', 'li.group', [{
  title: '.dribbble-img strong',
  image: '.dribbble-img [data-src]@data-src',
}])

  .delay('1s', '10s')
  
  .paginate('.next_page@href')
  .limit(3)
  .write('results.json') </code></pre>

TypeError: x(...).delay is not a function
    at Object.<anonymous> (/Users/ksidpen/Desktop/album-module/index.js:27:6)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by matthewmueller** [comment]
Sorry about that, it's should be on the initial object:

```js
var x = Xray().delay('1s', '10s')
```

**Comment by ksidpen** [comment]
that explains that. Thank you :)
